services:
  solarwatch-db:
    image: postgres:16
    container_name: solarwatch-db
    environment:
      POSTGRES_DB: solarwatch
      POSTGRES_USER: solarwatch
      POSTGRES_PASSWORD: solarwatch
    ports:
      - "5430:5432"
    networks:
      - solarwatch-network

  solarwatch-app:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: solarwatch-app
    env_file:
      - .env.docker
    depends_on:
      - solarwatch-db
    ports:
      - "8080:8080"
    networks:
      - solarwatch-network



  solarwatch-frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: solarwatch-frontend
    env_file:
      - .env.docker
    ports:
      - "5173:5173"
    environment:
      - DOCKER=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - solarwatch-app
    networks:
      - solarwatch-network
    volumes:
      - ./frontend:/app
      - /app/node_modules


networks:
  solarwatch-network:
