services:
  db:
    image: postgres:16
    container_name: solarwatch-db
    environment:
      POSTGRES_DB: solarwatch
      POSTGRES_USER: solarwatch
      POSTGRES_PASSWORD: solarwatch
    ports:
      - "5430:5432"

  app:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: solarwatch-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/solarwatch
      SPRING_DATASOURCE_USERNAME: solarwatch
      SPRING_DATASOURCE_PASSWORD: solarwatch
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
